feat: add RDOC to token list
rsksmart/rif-rollup pull request #71
Opened 2023-06-06 16:51 UTC by jurajpiar

## What

-   Hardcode the value of RDOC in the price feeder to always return 1.

## Why

-  Add support for RDOC as token.

## Refs

-   [ROLLUP-158](https://rsklabs.atlassian.net/browse/ROLLUP-158)

2023-06-07 09:12 UTC, antomor requested changes
@jurajpiar @AndresQuijano I'd verify if we really need that env variable or if we don't by using the `zk` cli

2023-06-07 09:12 UTC, antomor commented on core/bin/zksync_api/src/fee_ticker/ticker_api/mod.rs
> +        env::set_var("DATABASE_URL", DATABASE_URL);
are we sure that we need this? have we tried to run the tests with `zk` as they are supposed to be run?

2023-06-07 09:12 UTC, antomor commented on core/bin/zksync_api/src/fee_ticker/ticker_api/mod.rs
> +        let actual_qoute = FeeTickerAPI::get_last_quote(&ticker_api, token)
```suggestion
        let actual_quote = FeeTickerAPI::get_last_quote(&ticker_api, token)
```

2023-06-07 09:12 UTC, antomor commented on core/bin/zksync_api/src/fee_ticker/ticker_api/mod.rs
> +        env::set_var("DATABASE_URL", DATABASE_URL);
Are we sure that we need this? Have we tried to run the tests with `zk` as they are supposed to be run?

2023-06-07 09:12 UTC, antomor commented on core/bin/zksync_api/src/fee_ticker/ticker_api/mod.rs
> +        let actual_qoute = FeeTickerAPI::get_last_quote(&ticker_api, test_token_symbol)
```suggestion
        let actual_quote = FeeTickerAPI::get_last_quote(&ticker_api, test_token_symbol)
```

2023-06-13 09:14 UTC, jurajpiar commented
actually this doesn't seem to compile so I'm not sure why it was ready for review.

2023-06-13 09:49 UTC, closed without merging